config/routes.rb
Rails.application.routes.draw do
    resources :events
    resources :members
    resources :products do
    collection { post :import }
  end
   resources :tests
   resources :logs do
   collection { post :import }
 end
   resources :products
   resources :posts do
    collection { post :import }
   end
   resources :dazhongs

   resources :galaxy_macaus
   resources :huiyuans
   devise_for :users
   resources :users
   resources :galaxy_macaus
   resources :associators
   root :to => "home#index"
   mount RailsAdmin::Engine => 'admin', as: 'rails_admin'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      if user.admin?
        can :manage, :all
      if user.manage?
        can :read, :all
      else
        cannot :read, :Log
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/dazhong.rb
class Dazhong < ActiveRecord::Base
end

app/models/galaxy_macau.rb
class GalaxyMacau < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
  # attr_accessor :id, :major, :minor, :distance, :ip, :date, :time

  # validates_presence_of :price

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |log|
        csv << log.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|
      log.create! row.to_hash
    end
  end

  #   def self.open_spreadsheet(file)
  #   case File.extname(file.original_filename)
  #   when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
  #   when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  #   when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  #   else raise "Unknown file type: #{file.original_filename}"
  #   end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :manage, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      if User.count == 1
        resource.add_user.role 'admin'
      end
      resource
    end
    root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  layout :layout_by_resource
  protected
  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end
  # before_action :set_locale

 # def set_locale
 #   I18n.locale = params[:locale] || I18n.default_locale
 # end
end

app/controllers/dazhongs_controller.rb
class DazhongsController < ApplicationController
	def index
		# @dazhongs = Dazhong.all
		@dazhongs = Dazhong.page params[:page]
		@search = Dazhong.ransack(params[:q])
		@dazhongs = @search.result
	end
end

app/controllers/galaxy_macaus_controller.rb
class GalaxyMacausController < ApplicationController
	def index
		# @galaxy_macaus = GalaxyMacau.all
		@galaxy_macaus = GalaxyMacau.page params[:page]
		@search = GalaxyMacau.ransack(params[:q])
		@galaxy_macaus = @search.result
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
	load_and_authorize_resource
	# def index
	# 	# @logs = Log.page params[:page]
	# 	q_param = params[:q]
	# 	page = params[:page]
	# 	per_page = params[:per_page]
	#
	# 	@search = Log.ransack(params[:q])
  #   @logs = @search.result.page(page).per(per_page)
	#
	# end
	def index
		@logs = Log.page params[:page]
		q_param = params[:p]
		page = params[:page]
		per_page = params[:per_page]

		@search = Log.ransack(params[:q])
    @logs = @search.result.page(page).per(per_page)
		respond_to do |format|
			format.html
			format.csv { send_data @logs.to_csv }
			format.xls # { send_data @products.to_csv(col_sep: "\t") }
		end
	end

	def import
		Log.import(params[:file])
		redirect_to logs_url, notice: "logs imported."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :root, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dazhongs_helper.rb
module DazhongsHelper
end

app/helpers/galaxy_macaus_helper.rb
module GalaxyMacausHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dazhongs/_form.html.erb
<%= simple_form_for @dazhong, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :chudian %>
  <%= error_span(@dazhong[:chudian]) %>
  <%= f.input :openid %>
  <%= error_span(@dazhong[:openid]) %>
  <%= f.input :url %>
  <%= error_span(@dazhong[:url]) %>
  <%= f.input :time %>
  <%= error_span(@dazhong[:time]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dazhongs_path, :class => 'btn btn-default' %>
<% end %>

app/views/dazhongs/edit.html.erb
<%- model_class = Dazhong -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dazhongs/index.html.erb
<%- model_class = Dazhong -%>
<div class="page-header">
  <h1><%=t 'dazhongs' %></h1>
  <%= search_form_for @search do |f| %>
  <%= f.label :chudian %>
  <%= f.search_field :chudian_cont %>
  <%= f.label :openid %>
  <%= f.search_field :openid_cont %>
  <%= f.submit "search" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:chudian) %></th>
      <th><%= model_class.human_attribute_name(:openid) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
    </tr>
  </thead>
  <tbody>
    <% @dazhongs.each do |dazhong| %>
      <tr>
        <td><%= dazhong.id %></td>
        <td><%= dazhong.chudian %></td>
        <td><%= dazhong.openid %></td>
        <td><%= dazhong.url %></td>
        <td><%= dazhong.time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dazhongs/new.html.erb
<%- model_class = Dazhong -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dazhongs/show.html.erb
<%- model_class = Dazhong -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:chudian) %>:</strong></dt>
  <dd><%= @dazhong.chudian %></dd>
  <dt><strong><%= model_class.human_attribute_name(:openid) %>:</strong></dt>
  <dd><%= @dazhong.openid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @dazhong.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
  <dd><%= @dazhong.time %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              dazhongs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_dazhong_path(@dazhong), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dazhong_path(@dazhong),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/galaxy_macaus/_form.html.erb
<%= simple_form_for @galaxy_macau, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :contact %>
  <%= error_span(@galaxy_macau[:contact]) %>
  <%= f.input :openid %>
  <%= error_span(@galaxy_macau[:openid]) %>
  <%= f.input :url %>
  <%= error_span(@galaxy_macau[:url]) %>
  <%= f.input :time %>
  <%= error_span(@galaxy_macau[:time]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galaxy_macaus_path, :class => 'btn btn-default' %>
<% end %>

app/views/galaxy_macaus/edit.html.erb
<%- model_class = GalaxyMacau -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galaxy_macaus/index.html.erb
<%- model_class = GalaxyMacau -%>
<div class="page-header">
  <h1><%=t 'galaxy_macaus' %></h1>
  <%= search_form_for @search do |f| %>
  <%= f.label :contact %>
  <%= f.search_field :contact_cont %>
  <%= f.label :openid %>
  <%= f.search_field :openid_cont %>
  <%= f.submit "search" %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:openid) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
    </tr>
  </thead>
  <tbody>
    <% @galaxy_macaus.each do |galaxy_macau| %>
      <tr>
        <td><%= galaxy_macau.id %></td>
        <td><%= galaxy_macau.contact %></td>
        <td><%= galaxy_macau.openid %></td>
        <td><%= galaxy_macau.url %></td>
        <td><%= galaxy_macau.time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/galaxy_macaus/new.html.erb
<%- model_class = GalaxyMacau -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>CRM</title>

    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->
    <%= stylesheet_link_tag 'bootstrap.min' %>
    <%= stylesheet_link_tag 'font-awesome' %>

  <!--   <link href="font-awesome/css/font-awesome.css" rel="stylesheet"> -->

    <!-- Toastr style -->
    <%= stylesheet_link_tag 'toastr.min' %>
 <!--    <link href="css/plugins/toastr/toastr.min.css" rel="stylesheet"> -->

    <!-- Gritter -->
    <%= stylesheet_link_tag 'jquery.gritter' %>
    <%= stylesheet_link_tag 'animate' %>
    <%= stylesheet_link_tag 'style' %>
<!--     <link href="js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet"> -->

</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <h3>CRM</h3>



                           <p class="notice"><%= notice %></p>
                           <p class="alert"><%= alert %></p>
                       <!--  <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="img/profile_small.jpg" />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">David Williams</strong>
                             </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="profile.html">Profile</a></li>
                                <li><a href="contacts.html">Contacts</a></li>
                                <li><a href="mailbox.html">Mailbox</a></li>
                                <li class="divider"></li>
                                <li><a href="login.html">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div> -->
                    </li>
                    <li>
                        <a href="index.html"><i class="fa fa-th-large"></i> <span class="nav-label">BasicInformation</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><%=link_to "MemberList" %></a></li>
                            <li><%=link_to "MemberInformationManagement" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "MemberAtributes" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "MemberPortraitManagement" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "MerchantManagement" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "ReportForm" %></a></li>   <!-- 未加链接地址 -->
                        </ul>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">ActivityManagement</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><%=link_to "HistoricalEventManagement" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "NewEventManagement" %></a></li>   <!-- 未加链接地址 -->
                        </ul>
                    </li>


                    <li>
                        <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">InterfaceManage</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><%=link_to "WeChatShakeDate",logs_path %></a></li>
                            <li><%=link_to "VolkswagenData",dazhongs_path %></a></li>
                            <li><%=link_to "GalaxyMacau",galaxy_macaus_path %></a></li>
                            <li><%=link_to "InterfaceList" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "InterfaceDataAcquisition" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "NewInterfaceManagement" %></a></li>   <!-- 未加链接地址 -->
                        </ul>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-files-o"></i> <span class="nav-label">IntegralManagement</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><%=link_to "IntegralMall" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "IntegralImport" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "IntegralDerivation" %></a></li>   <!-- 未加链接地址 -->
                        </ul>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-flask"></i> <span class="nav-label">SystemManagement</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><%=link_to "SystemLog" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "AuthorityManagement" %></a></li>   <!-- 未加链接地址 -->
                            <li><%=link_to "OtherManagement" %></a></li>   <!-- 未加链接地址 -->
                        </ul>
                    </li>
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <%= link_to "English", :locale=>'en' %>

                </li>
                <li class="dropdown">
                    <%= link_to "简体中文", :locale=>'zh_CN' %>

                </li>
                <li class="dropdown">
                    <%= link_to "繁體中文", :locale=>'zh' %>

                </li>
                <li class="dropdown">
                    <%= link_to "日本語", :locale=>'ro' %>

                </li>
                <li>
                     <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                </li>
                <li>
                    <a class="right-sidebar-toggle">
                        <i class="fa fa-tasks"></i>
                    </a>
                </li>
            </ul>

        </nav>
            <%= yield %>
        </div>
                <div class="footer">
                    <div class="pull-right">
                         <strong>CRM</strong>
                    </div>
                    <div>
                        Copyright<strong> Moboplus</strong> &copy; 2016
                    </div>
                </div>
            </div>
        </div>

        </div>
    </div>

    <!-- Mainly scripts -->
    <%= javascript_include_tag "jquery-2.1.1" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "jquery.metisMenu" %>
    <%= javascript_include_tag "jquery.slimscroll.min" %>


    <!-- Flot -->
    <%= javascript_include_tag "jquery.flot.js" %>
    <%= javascript_include_tag "jquery.flot.tooltip.min.js" %>
    <%= javascript_include_tag "jquery.flot.spline.js" %>
    <%= javascript_include_tag "jquery.flot.resize" %>
    <%= javascript_include_tag "jquery.flot.pie" %>


    <!-- Peity -->
    <%= javascript_include_tag "jquery.peity.min" %>
    <%= javascript_include_tag "peity-demo" %>

    <!-- Custom and plugin javascript -->
    <%= javascript_include_tag "inspinia" %>
    <%= javascript_include_tag "pace.min" %>

    <!-- jQuery UI -->
    <%= javascript_include_tag "jquery-ui.min" %>

    <!-- GITTER -->
    <%= javascript_include_tag "jquery.gritter.min" %>

    <!-- Sparkline -->
    <%= javascript_include_tag "jquery.sparkline.min" %>

    <!-- Sparkline demo data  -->
    <%= javascript_include_tag "sparkline-demo" %>

    <!-- ChartJS-->
    <%= javascript_include_tag "Chart.min" %>

    <!-- Toastr -->
    <%= javascript_include_tag "toastr.min" %>


    <script>
        $(document).ready(function() {
            setTimeout(function() {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.success('Welcome to CRM');

            }, 1300);


            var data1 = [
                [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,30],[11,10],[12,13],[13,4],[14,3],[15,3],[16,6]
            ];
            var data2 = [
                [0,1],[1,0],[2,2],[3,0],[4,1],[5,3],[6,1],[7,5],[8,2],[9,3],[10,2],[11,1],[12,0],[13,2],[14,8],[15,0],[16,0]
            ];
            $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
                data1, data2
            ],
                    {
                        series: {
                            lines: {
                                show: false,
                                fill: true
                            },
                            splines: {
                                show: true,
                                tension: 0.4,
                                lineWidth: 1,
                                fill: 0.4
                            },
                            points: {
                                radius: 0,
                                show: true
                            },
                            shadowSize: 2
                        },
                        grid: {
                            hoverable: true,
                            clickable: true,
                            tickColor: "#d5d5d5",
                            borderWidth: 1,
                            color: '#d5d5d5'
                        },
                        colors: ["#1ab394", "#464f88"],
                        xaxis:{
                        },
                        yaxis: {
                            ticks: 4
                        },
                        tooltip: false
                    }
            );

            var doughnutData = [
                {
                    value: 300,
                    color: "#a3e1d4",
                    highlight: "#1ab394",
                    label: "App"
                },
                {
                    value: 50,
                    color: "#dedede",
                    highlight: "#1ab394",
                    label: "Software"
                },
                {
                    value: 100,
                    color: "#b5b8cf",
                    highlight: "#1ab394",
                    label: "Laptop"
                }
            ];

            var doughnutOptions = {
                segmentShowStroke: true,
                segmentStrokeColor: "#fff",
                segmentStrokeWidth: 2,
                percentageInnerCutout: 45, // This is 0 for Pie charts
                animationSteps: 100,
                animationEasing: "easeOutBounce",
                animateRotate: true,
                animateScale: false
            };

            var ctx = document.getElementById("doughnutChart").getContext("2d");
            var DoughnutChart = new Chart(ctx).Doughnut(doughnutData, doughnutOptions);

            var polarData = [
                {
                    value: 300,
                    color: "#a3e1d4",
                    highlight: "#1ab394",
                    label: "App"
                },
                {
                    value: 140,
                    color: "#dedede",
                    highlight: "#1ab394",
                    label: "Software"
                },
                {
                    value: 200,
                    color: "#b5b8cf",
                    highlight: "#1ab394",
                    label: "Laptop"
                }
            ];

            var polarOptions = {
                scaleShowLabelBackdrop: true,
                scaleBackdropColor: "rgba(255,255,255,0.75)",
                scaleBeginAtZero: true,
                scaleBackdropPaddingY: 1,
                scaleBackdropPaddingX: 1,
                scaleShowLine: true,
                segmentShowStroke: true,
                segmentStrokeColor: "#fff",
                segmentStrokeWidth: 2,
                animationSteps: 100,
                animationEasing: "easeOutBounce",
                animateRotate: true,
                animateScale: false
            };
            var ctx = document.getElementById("polarChart").getContext("2d");
            var Polarchart = new Chart(ctx).PolarArea(polarData, polarOptions);

        });
    </script>
</body>
</html>

app/views/logs/index.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t 'logs' %></h1>
  <%= search_form_for @search do |f| %>
  <%= f.label :ip %>
  <%= f.search_field :ip_cont %>
  <%= f.label :distance %>
  <%= f.search_field :distance_cont %>
  <%= f.label :date %>
  <%= f.search_field :date_cont %>
  <%= f.submit "search" %>
  <% end %>

Download:
<%= link_to "CSV", logs_path(format: "csv") %> |
<%= link_to "Excel", logs_path(format: "xls") %>
<%= form_tag import_logs_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Import" %>
<% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:uuid) %></th>
      <th><%= model_class.human_attribute_name(:major) %></th>
      <th><%= model_class.human_attribute_name(:minor) %></th>
      <th><%= model_class.human_attribute_name(:distance) %></th>
      <th><%= model_class.human_attribute_name(:ip) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.id %></td>
        <td><%= log.uuid %></td>
        <td><%= log.major %></td>
        <td><%= log.minor %></td>
        <td><%= log.distance %></td>
        <td><%= log.ip %></td>
        <td><%= log.date %></td>
        <td><%= log.time %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @logs %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>